name: publish

on:
    workflow_dispatch: # Allow manual trigger
    release:
        types: [created]

jobs:
    publish-sardinecan:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Get version
              run: |
                  echo "VERSION=$(cat VERSION.txt)" >> $GITHUB_ENV

            - name: Build the SardineCan Docker image
              run: |
                  echo "Building SardineCan docker in ${{ env.VERSION }}"
                  echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
                  docker build --tag ghcr.io/merschformann/sardinecan:latest --tag ghcr.io/merschformann/sardinecan:${{ env.VERSION }} -f Dockerfile ..
                  docker push ghcr.io/merschformann/sardinecan:latest
                  docker push ghcr.io/merschformann/sardinecan:${{ env.VERSION }}
              working-directory: ./SC.Service
