name: publish

# on:
#   release:
#     types: [created]

on: [workflow_dispatch]

defaults:
  run:
    working-directory: ./SC.Service

jobs:
  publish-sardinecan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get version
      run: |
        VERSION=$(cat VERSION.txt)

    - name: Build the SardineCan Docker image
      run: |
        echo "Building SardineCan docker in $VERSION"
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker build . --tag ghcr.io/merschformann/sardinecan:latest --tag ghcr.io/merschformann/sardinecan:$VERSION
        docker push ghcr.io/merschformann/sardinecan
